// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGevL15C4Pj4eoujsAMcbISL8L8XXt-Fs',
    appId: '1:909884512613:android:35725c25be9e1ee004298c',
    messagingSenderId: '909884512613',
    projectId: 'chatapp-e1a0f',
    storageBucket: 'chatapp-e1a0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfAm8vkZGBzPwrWMCAWEEmHRyLaceIEMo',
    appId: '1:909884512613:ios:ce0379cd7fc3740c04298c',
    messagingSenderId: '909884512613',
    projectId: 'chatapp-e1a0f',
    storageBucket: 'chatapp-e1a0f.firebasestorage.app',
    androidClientId: '909884512613-pn2m6ajd70f2u5lgh6nqi75o7mhb1di9.apps.googleusercontent.com',
    iosClientId: '909884512613-rkr09m1023cdm2u1qosdrgpn29kji89m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

}